<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 3.5.5 setup script
 * Date: Mon, 14 Jan 2013 10:35:00 -0500
 */

/* Servers configuration */
$i = 0;

/* Server: lamp-crm [1] */
$i++;
$cfg['Servers'][$i]['verbose'] = 'lamp-crm';
$cfg['Servers'][$i]['host'] = 'localhost';
$cfg['Servers'][$i]['port'] = '';
$cfg['Servers'][$i]['socket'] = '';
$cfg['Servers'][$i]['connect_type'] = 'socket';
$cfg['Servers'][$i]['extension'] = 'mysqli';
$cfg['Servers'][$i]['compress'] = true;
$cfg['Servers'][$i]['auth_type'] = 'cookie';
$cfg['Servers'][$i]['user'] = 'crm';
$cfg['Servers'][$i]['password'] = 'crm.p';
$cfg['Servers'][$i]['only_db'] = array('crm');
$cfg['Servers'][$i]['ssl'] = true;

/* End of servers configuration */

$cfg['blowfish_secret'] = '50f4256bbdd628.78886339';
$cfg['DefaultLang'] = 'en';
$cfg['ServerDefault'] = 1;
$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';
?>