<?php

 /*********************************************************************************
  /*********************************************************************************
  * File generated by the Sugar Translation Suite (Contributor : www.grupa-atlantis.pl)
  *********************************************************************************/
  /*********************************************************************************
  * $Header: modules/OAuthTokens/language/fr_FR.lang.php,  Tue 20/12/11 15:23:18 
  * Description : .
  * Portions created by SugarCRM are Copyright (C) SugarCRM, Inc. All Rights Reserved.
  * Traduction par CARRENET
  *   www.carrenet.com - info@carrenet.com
  *********************************************************************************/

if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');

$mod_strings = array ( 
   'LBL_OAUTH_REQUEST' => 'Requête du token' ,
   'LBL_OAUTH_AUTHORIZE' => 'Autoriser l&#039;élément' ,
   'LBL_OAUTH_CONSUMERREQ' => 'Autoriser le token pour consumer %s?' ,
   'LBL_OAUTH_ROLE' => 'Rôle de l&#039;élement' ,
   'LBL_OAUTH_VALIDATION' => 'Code de vérification' ,
   'LBL_ASSIGNED_TO_NAME' => 'Utilisateur' ,
   'LBL_ID' => 'ID' ,
   'LBL_STATUS' => 'Statut' ,
   'LBL_TS' => 'Horodatage' ,
   'LBL_LIST_DELETE' => 'Supprimer l&#039;élément' ,
   'LBL_CONSUMER' => 'Nom Consumer' ,
   'LBL_OAUTH_DISABLED' => 'Le support OAuth n&#039;est pas autorisé. L&#039;extension PHP oauth peut être manquante. Veuillez contacter votre administrateur.' );

?>
